### ISSUE TITLE
handle version conflicts

### ISSUE THREAD

**Issue by deepstreamIO** [deepstreamIO/deepstream.io#1] opened 2015-01-12 10:28 UTC
Merge changes on top of incoming update and re-issue

What if both changes are for the same path? Set merge strategy as option? On Record or on client level?

**Comment by rquast** [comment] 2015-06-22 09:55
Awesome project! The only thing that's stopping me from using it would be this issue (first question I had when I started looking at it).

**Comment by yasserf** [comment] 2016-05-11 20:56
Closing as duplicate of #137, which should be merged very soon!

**Closed** 2016-05-17 12:05 UTC
Labels: enhancement, in review
