### ISSUE TITLE
cleanup demo and example repositories

### ISSUE THREAD

**Issue by timaschew** [deepstreamIO/deepstream.io#264] opened 2016-07-05 13:10 UTC
see #262 

We should find a solution for all our repos to get both client and server installed against latest stable version, so that they will always work.
Ideally without pinning the version.

Proposal: add both client and server as a dependency in the package.json

**Comment by yasserf** [comment] 2016-07-10 15:18
Closing as duplicate of 
https://github.com/deepstreamIO/deepstream.io/issues/183

**Closed by yasserf** 2016-07-10 15:18 UTC
Labels: duplicate
