### ISSUE TITLE
Create a React Native Wrapper for the deepstream.io JS client

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#76] opened 2016-01-13 14:54 UTC

**Comment by datapimp** [comment] 2016-03-02 02:22
Hi I could take this on -- can you offer any starting advice?

**Comment by WolframHempel** [comment] 2016-03-03 09:14
Hi @datapimp , thanks for looking into this. We've lately been working on a react mixin that bidirectionally syncs a component's state with a deepstream record - it still has quite a bit of way to go, but it might help with the initial thinking about how the two could interact.

https://github.com/deepstreamIO/deepstream.io-tools-react

I'm very in your thoughts about whether to take a similar route with the react native wrapper or if another approach might make more sense.

**Comment by aurelien-ctouch** [comment] 2016-09-13 22:03
Hi, Deepstream is very impressive and very well designed. 
Does anyone can report success into integrating deepstream js client with react native ?
Any pifall to be aware of ?

**Comment by aurelien-ctouch** [comment] 2016-09-16 07:01
I can not make it work: stuck on error "Requiring unknown module "xmlhttprequest-ssl".
I tried to npm install this module, but I guess it can not run inside react-native.

**Comment by yasserf** [comment] 2016-09-16 10:07
@aurelien-ctouch hey, thats quite interesting!

We are actually moving away from engine.io and will be using pure websockets instead. This will give us much better performance ( only downside is dropping support for legacy browsers ).

I'll take a look and see what the difference between the package you suggested and the official one is, and if it isn't catastrophic will swap them out in a near release!

**Comment by aurelien-ctouch** [comment] 2016-09-16 23:30
It works :).
I reproduced the "getting started" sample on my android simulator. Of course it's experimental.

- I have forked the react-native-engine.io-client
- Got rid of the import xmlhttprequest-ssl
- I have forked your js client
- Taken care of net dependency by adding the react-native-engine.io-client, and adding "browser": {   "net": "react-native-tcp"  } in the package.json
- Added dependency to url package

**Comment by yasserf** [comment] 2016-09-17 11:31
Sounds good!

We are going to be looking at moving over to websockets by the end of october, because it's quite near I don't think we will be swapping out the official engine.io client due to qa overhead until then! Your fork should be a great place to do react native development until we have pure websocket support out!

**Comment by babnik63** [comment] 2016-12-04 22:18
Is there any update? Are we going to have React native support?

**Comment by Dranithix** [comment] 2016-12-24 16:48
Would like to know if any update is to be made soon to support React Native; a real-time backend is typically crucial for mobile applications.

**Comment by andyhu** [comment] 2016-12-24 16:57
+1 React Native support is quite important

**Comment by yasserf** [comment] 2016-12-25 18:52
As far as I know this should now work since we are using normal websockets. We'll try and get a hello world react native tutorial out to demonstrate it. Thanks!

**Comment by Dranithix** [comment] 2016-12-25 19:09
Just wanted to confirm it is working now using the JS connector, tested it on my app. and planning to test it out commercially :).

**Comment by mindwave** [comment] 2016-12-25 23:51
@Dranithix Excellent news! Can you provide a bit more detail on how you got this to work?

**Comment by mindwave** [comment] 2016-12-26 18:13
I seem to have an issue with react-native finding one of the Deepstream dependency modules, although it does exist within the listed directory. Here is the error message when the app is run:
```
Unable to resolve module url from /Users/myDir/Documents/ReactNative/Deepstream/node_modules/deepstream.io-client-js/src/utils/utils.js: Module does not exist in the module map or in these directories:
  /Users/myDir/Documents/ReactNative/Deepstream/node_modules
```

**Comment by Dranithix** [comment] 2016-12-26 18:40
Just do `npm install url --save` and it should be fine. There should be no other dependencies which the `url` library requires.

**Comment by mindwave** [comment] 2016-12-26 19:01
Thank you, working now!

**Comment by quadsurf** [comment] 2017-01-03 17:54
@yasserf will a link to that 'hello world' react-native app be posted/added to: https://deepstream.io/tutorials/
or just posted here in this GH issue tracker?

**Comment by yasserf** [comment] 2017-01-03 19:18
Would be on the tutorials page. We have a bit of backlog in terms of requests and features so it may take a bit of time, but if someone is willing/has experience with react native we would be very grateful for a PR!

**Comment by isilher** [comment] 2017-01-27 15:54
I made a PR for a simple tutorial: https://github.com/deepstreamIO/deepstream.io-website/pull/119

**Comment by isilher** [comment] 2017-02-10 14:56
It was merged in and is available at https://deepstream.io/tutorials/integrations/frontend-reactnative/. 

I suppose this issue can be closed @WolframHempel?

**Closed** 2019-06-01 18:27 UTC
Labels: help-wanted
