### ISSUE TITLE
deepstream 4.0.0-rc.3 and mongodb

### ISSUE THREAD

**Issue by jonno317** [deepstreamIO/deepstream.io#880] opened 2018-02-06 19:52 UTC
Having an issue with the mongo integration for deepstream 4. On a deepstream server restart, the deepstream server appears to be unaware of the existing records in mongodb. Checking the mongo database directly shows records are being created properly, but after a restart deepstream does not retrieve lists or records previously created.

**Comment by yasserf** [comment] 2018-02-09 12:59
Hey! Closing this as a duplicate of https://github.com/deepstreamIO/deepstream.io/issues/878 (different connector, same concept)

**Closed by yasserf** 2018-02-09 12:59 UTC
