### ISSUE TITLE
Cannot start the server release 6.2.1 from the command line (Linux)

### ISSUE THREAD

**Issue by patrickomatik** [deepstreamIO/deepstream.io#1124] opened 2022-10-28 17:57 UTC
**Description**
I am falling at the first hurdle. I am following the instructions to set up a deepstream server under linux linked here: [[https://deepstream.io/tutorials/install/linux/]]. The github release 6.2.1 errors out on a vanilla ubuntu LTS-20.04 install

```console
deepstream.service - deepstream
     Loaded: loaded (/etc/systemd/system/deepstream.service; disabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-10-28 17:40:23 UTC; 2s ago
   Main PID: 60526 (deepstream)
      Tasks: 6 (limit: 9249)
     Memory: 39.1M
        CPU: 463ms
     CGroup: /system.slice/deepstream.service
             `-60526 /root/deepstream/deepstream daemon -c /etc/deepstream

Oct 28 17:40:24 redacted deepstream[60526]:   ^
Oct 28 17:40:24 redacted deepstream[60526]: Error: Cannot find module '/start'
Oct 28 17:40:24 redacted deepstream[60526]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
Oct 28 17:40:24 redacted deepstream[60526]:     at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
Oct 28 17:40:24 redacted deepstream[60526]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
Oct 28 17:40:24 redacted deepstream[60526]:     at Function.runMain (pkg/prelude/bootstrap.js:1847:12)
Oct 28 17:40:24 redacted deepstream[60526]:     at internal/main/run_main_module.js:17:47 {
Oct 28 17:40:24 redacted deepstream[60526]:   code: 'MODULE_NOT_FOUND',
Oct 28 17:40:24 redacted deepstream[60526]:   requireStack: []
Oct 28 17:40:24 redacted deepstream[60526]: }
```

Where redacted is the hostname.

**To Reproduce**

As root:

1. wget https://github.com/deepstreamIO/deepstream.io/releases/download/v6.2.1/deepstream.io-linux-6.2.1.tar.gz 
2. tar -zxvf deepstream.io-linux-6.2.1.tar.gz 
3. ./deepstream start

**Server version**
Attempting to install: ```Deepstream 6.2.1```

**Server OS**
```console 
lsb_release -a
```

yields
```console
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```
**Node version**
```npm 8.6.0```

**Comment by jaime-ez** [comment] 2022-11-02 19:57
Hi, i can't reproduce the error. just launched a droplet with ubuntu 20.04, copy pasted your commands and it works...did you installed it as a service also or not?

**Comment by patrickomatik** [comment] 2022-11-04 11:10
Thanks for taking the time to investigate this. I am using a minimal ubuntu server install. There seem to be some path-related issues which can be resolved by simply running ```npm start``` in the bin directory. ```npm``` then complains about a missing packages.json, but deepstream then runs from the cli. Whatever the underlying config issue is, it is still unresolved for running as a service, which still fails. I suspect the issue is trivial for someone who is familiar with the nuances of ```npm``` - sadly that isn't me :-)

**Comment by jaime-ez** [comment] 2022-11-05 13:44
Hi, there seems to be a confusion, please let me know if the docs at https://deepstreamio.github.io/ are not clear regarding this:

You can use deepstream as a standalone binary OR as a nodejs module.

When you install the binary (downloading from releases as you did) there is no need for nodejs, everything comes bundled in an executable. After decompressing you run using this command `./deepstream start` there is no need to install nodejs and if you execute `npm` commands you will get an error and it will not work as intended. Other CLI options can be reached using `./deepstream -h`.

**Comment by jaime-ez** [comment] 2022-12-02 17:58
closing, feel free to ask more question if you have

**Closed by jaime-ez** 2022-12-02 17:58 UTC
