### ISSUE TITLE
non-existant record

### ISSUE THREAD

**Issue by thorsby** [deepstreamIO/deepstream.io#983] opened 2019-08-28 18:07 UTC
I have a fresh (version 4.0.6) version of server on Mac/10.12.6
I'm running the quick start tutorial on the deepstream.io website:
https://deepstream.io/tutorials/getting-started/javascript/index.html

When the client connects, I get the following on server: 
```
INCOMING_CONNECTION | from undefined (127.0.0.1)
AUTH_SUCCESSFUL | open
VERSION_EXISTS | open tried to update record some-name to version 0 but it already was 0
```

So already on connect, there is a warning.
As soon as I try typing in the HTML input field, I get errors on the server:
```
RECORD_UPDATE_ERROR | Received update for non-existant record some-name
```

I tried replacing the server binary with a version running in NodeJS and swapping between client from CDN and NPM.

This example is very simple and pretty coherent with the documentation on records.
What am I missing? Is something broken?

**Comment by yasserf** [comment] 2019-08-29 09:39
Hello! This was sadly a small regression in a recent release. A fix will be released in the next day or two.

**Comment by thorsby** [comment] 2019-08-29 19:20
Okay, thank you.
I got it working now with current server@4.0.6, but had to backstep client to 4.0.2.

**Comment by ilteblick** [comment] 2019-08-30 09:08
@thorsby Check this link pls https://deepstream.io/tutorials/upgrade-guides/v4/client/index.html. When i use `await client.login()` problem was resolved.

**Comment by yasserf** [comment] 2019-08-30 12:52
Yup! The issue is when you request a record before being logged in with offline disabled. There’s a lot of permutations, trying to find a way to simplify it a bit

**Comment by yasserf** [comment] 2019-08-30 19:23
Released 4.0.5 which should address this, please let me know if otherwise!

**Comment by yasserf** [comment] 2019-08-30 19:24
Was a client issue, hence the version number :D

**Closed by yasserf** 2019-08-30 19:23 UTC

**Comment by thorsby** [comment] 2019-09-03 19:39
> Was a client issue, hence the version number :D
Nice comment, actually clarified 👍 I did not initial realise that client and server was not on same schedule.
