### ISSUE TITLE
Support initvd/systemd in rpm and deb package for deepstream

### ISSUE THREAD

**Issue by randahlem** [deepstreamIO/deepstream.io#716] opened 2017-06-07 09:59 UTC
The plan is to support initvd and systemd inside the rpm/deb package for deepstream. According to yasserf: 
deepstreamIO/deepstream.io#711

According to os-service it autogenerates those scripts.

Option 2 is we provide a

deepstream service init etcd
deepstream service init initv

that is probably the easiest way of making it agnostic

https://docs.opsmanager.mongodb.com/current/tutorial/stop-using-automation/#the-make-init-scripts-tool

PR is here: https://github.com/deepstreamIO/deepstream.io/pull/683

**Comment by randahlem** [comment] 2017-06-08 08:18
@yasserf I like the second idea, to bake it into deepstream to let the user choose. we basically have the init scripts ready. We just need someone to implement the "service init". Which copy over the scripts and register the services and hook them into autostart.

**Comment by yasserf** [comment] 2017-06-29 08:29
Duplicate of 711

**Closed** 2017-06-29 08:29 UTC
