### ISSUE TITLE
/usr/bin/env: „node\r“ No such file

### ISSUE THREAD

**Issue by somniumAeternam** [deepstreamIO/deepstream.io#316] opened 2016-08-01 20:58 UTC
I'm running openSUSE Tumbleweed and installed deepstream.io via npm globally:

`npm install -g deepstream.io`

After trying to start deepstream, the following error occured:

> /usr/bin/env: „node\r“ No such file

It looks like an error in the file format in the script deepstream. It can be solved by changing the file format to unix, e.g. with vim (:set ff=unix).

**Comment by yasserf** [comment] 2016-08-02 07:40
Thanks for raising. We have discovered the issue recently as well (#277), we published from a windows machine and that caused the issue. We are looking to publish directly from CI on tags which should solve this on the long run!

**Comment by yasserf** [comment] 2016-08-28 10:28
duplicate of #277

**Closed** 2016-10-10 09:40 UTC
