### ISSUE TITLE
Unable to fetch data from Rethink, Mongo DB after deepstream server restart

### ISSUE THREAD

**Issue by itwalton** [deepstreamIO/deepstream.io#889] opened 2018-03-05 19:31 UTC
Hello,

**Problem:** The Mongo and Rethink connectors are writing to the datastore properly, but won't read from the database after deepstream is restarted.

**Setup:**
- Environment (Node v9.5.0)
- Deepstream Server (v4.0.0-rc.4)
- Deepstream Client (v4.0.0-beta.1 - v4 branch)
- MongoDB / RethinkDB adapters
-- Passing storage data in deepstream server config

**Steps to Reproduce:**
1) Configure deepstream server with either adapter
```yaml
storage:
    name: rethinkdb
    options:
      host: 'localhost'
      port: 28015
      splitChar: '/'
```

2) Boot deepstream server
3) Create a record
_Note: The record is written to the database as expected_
```javascript
const record = await client.record.getRecord('test/A').whenReady();
record.set({ test: 'this' })
```
4) Restart deepstream
5) Attempt to fetch the record
_Note: An empty object is returned_
```javascript
const record = await client.record.getRecord('test/A').whenReady();
console.log(record) // => {}
```

**EDIT (06-MAR-2018):** Add `await` to examples

Thanks,
Ian

**Comment by yasserf** [comment] 2018-03-06 09:35
thanks for raising.

In regards to whenReady, you should either use async/await, a callback or a promise

```
const record = client.record.getRecord('test/A').whenReady()
await record.whenReady()
record.set({ test: 'this' })
```

otherwise its sync and it won't manage to load it in time. Is that the problem?

**Comment by itwalton** [comment] 2018-03-06 15:36
Hi @yasserf,

I am awaiting the records in the real code, but had forgotten to await in the pseudo-code above.

Apologies,
Ian

**Comment by daviderenger** [comment] 2018-03-06 17:48
I can confirm that this is the case, its the cause of #887 too.

Trying to do a snapshot fails with record not found but getRecord will "reset" the data in db back to an empty object with version 0.

I'll do some debugging now to find out where it goes wrong.

**Comment by daviderenger** [comment] 2018-03-06 17:58
Row 63 in record-request.js

`       services.storage.get(recordName, (storageError, version, result) => {
            if (!storageTimedOut) {
                clearTimeout(storageTimeout);
                onStorageResponse(storageError, recordName, version, data, socketWrapper, onComplete, onError, services, context, metaData, message);
            }
        }, metaData);
`

onStorageResponse should be called with "result" instead of "data".

With that change it works!

**Comment by yasserf** [comment] 2019-04-07 22:43
Seems this fix was in v3 but wasn't ported or released 😕? Closing but please let me know if its still an issue

**Closed by yasserf** 2019-04-07 22:43 UTC
