### ISSUE TITLE
Cannot read property 'isReady' of undefined

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#284] opened 2016-07-13 08:23 UTC
Could at least print which dependency failed.

``` javascript
/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/deepstream.io/src/utils/dependency-initialiser.js:23
    if( this._dependency.isReady ) {
                        ^

TypeError: Cannot read property 'isReady' of undefined
    at new DependencyInitialiser (/node_modules/deepstream.io/src/utils/dependency-initialiser.js:23:22)
    at Deepstream.start (/node_modules/deepstream.io/src/deepstream.io.js:136:26)
    at Object.<anonymous> (server.js:85:4)
    at Module._compile (module.js:541:32)
    at loader (/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/src/index.js:2:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

**Comment by yasserf** [comment] 2016-07-13 08:49
Agreed, this is a quick win so we'll do it sooner than later =)

**Comment by yasserf** [comment] 2016-07-20 07:19
Done in 1.0.2

**Comment by yasserf** [comment] 2016-07-20 07:19
Woah

**Comment by yasserf** [comment] 2017-02-07 14:10
Closing since I can't reproduce

**Closed by yasserf** 2017-02-07 14:10 UTC
Labels: awaiting feedback, bug, enhancement, roadmap

**Comment by bbobbly** [comment] 2017-04-19 17:51
Yasserf I am getting this error, "Cannot read property 'isReady' of undefined", when trying to import "const fetch = require('electron-fetch');" in a javascript file called by a HTML file in my Electron app.

**Comment by yasserf** [comment] 2017-04-19 19:57
This error is in server... how are you using deepstream with electron?
