### ISSUE TITLE
UNSOLICITED MESSAGE: invalid rpc correlation for rpc

### ISSUE THREAD

**Issue by HarshOB** [deepstreamIO/deepstream.io#904] opened 2018-08-03 07:09 UTC
**1) server.js (Used: NodeJS)**
 

    const ds = deepstream('<URL>');
    const randomURL = Math.ceil(Math.random() * 10000).toString();
    ds.rpc.provide(randomURL, (data, response) => {
      console.log("received request for: ", randomURL, data);
      response.send(`${Date.now()} Hello from random Service: ${randomURL}`);
    })

**2) client.js (Used: [microjs][1])**

    module.exports = async (req, res) => {
      let fullPath = req.url;
      fullPath = fullPath.split('/')[1];
      const result = await ds.rpc.make(fullPath, {}, (err, result) => {
        console.log("response received: ", err, result);
        res.end(result);
      });
      console.log(`result for ${fullPath} is: ${result}`);
    }

**after calling this URL several times I got error** 

    localhost:port/randomURL

**Comment by yasserf** [comment] 2019-06-09 13:30
Hey, I'm surprised the code you provided actually works since you can't have a promise and a callback at the sametime..

```
 await ds.rpc.make(fullPath, {}, (err, result) => {
    console.log("response received: ", err, result);
    res.end(result);
  });
```

Can you please provide a working sample? Thanks!

**Comment by yasserf** [comment] 2019-10-01 13:37
I'm going to close this issue because:

1) Client doesn't login
2) RPC doesn't use the correct signature

As such it's pretty hard for me to reproduce. If anyone encounters this issue again please provide some more detail and I'll be happy to investigate!

**Closed by yasserf** 2019-10-01 13:37 UTC
