### ISSUE TITLE
Presence offline while still connected

### ISSUE THREAD

**Issue by bartpeeters** [deepstreamIO/deepstream.io#729] opened 2017-06-19 08:03 UTC
We have a couple of devices that are 24/7 connected with the deepstream server. 
The first couple of days when we ask the presence of these devices they show up online, after 3 days or so they suddenly all go offline in presence. 
They are 100% still online because they provide a unique rpc call and when you use this rpc call they just respond, but presence still acts as if they are offline.

From what I can gather from the code, "client-connected" and "client-disconnected" events are used to determine the presence. The disconnected event is emitted in _onSocketClosed of "uws-connection-endpoint.js" so it leads me to believe this function is called while the socket is in fact still open?

**Comment by WolframHempel** [comment] 2017-06-19 13:22
Hi @bartpeeters - thanks for raising,happy to look into it asap. Could I ask you for a few more details though: 
- are you using deepstream to gather metrics from electricity meters? If so, what kind of operating system/client are you running?
- it is possible for a client to count as offline without invoking _onSocketClosed if multiple consecutive heartbeats are missed - are you using any special settings for heartbeatinterval or timeout?
- do you have any server logs that show how the clients disconnect?

Thanks so much,

Wolfram

**Comment by olofssonanton** [comment] 2017-06-20 09:42
We are also experiencing the same problem. Using these settings for our clients:
```
maxReconnectAttempts: Infinity,
reconnectIntervalIncrement: 1500,
heartbeatInterval: 10000,
maxReconnectInterval: 5000
```

**Comment by bartpeeters** [comment] 2017-06-23 08:01
This night it happened again. I checked the logs but there is nothing out of the ordinary. I'm using the default log level though. I'll change it to DEBUG and report back if I find something.

**Comment by yasserf** [comment] 2017-06-23 08:07
Thank you for the updates. We'll also add some more debug lines in the upcoming release to see if we can find out where the issue is coming from

**Comment by daviderenger** [comment] 2017-08-01 11:37
Any news on this? This is real for us and we rolled back to our own solution counting connections manually until this is solved.

**Comment by yasserf** [comment] 2020-05-03 07:53
Closing due to inactivity

**Comment by caracal7** [comment] 2021-11-03 08:10
I have absolutely the same issue with latest Deepstream(linux, node.js)
My microservices always disappeared from presence after few days of work. But microservices is alive and connected and RPCs is accessible.
No interesting in logs at all 🤔

**Comment by jaime-ez** [comment] 2021-11-08 23:57
Hi,  without some code to reproduce it's hard to fix...can you ran your server on DEBUG log level to see if anything shows?

There is a caveat with the presence.query call on the client (I think it's not properly documented):

- `client.presence.getAll()` : will return all connected clients leaving out the client who is making the query.
- `client.presence.getAll([userIds])` : will return the answer to the presence of the given userIds 

Here is the presence handler source if you can find anything: https://github.com/deepstreamIO/deepstream.io/blob/master/src/handlers/presence/presence-handler.ts

Are your services being authenticated ? Because if not, they will not show in presence...They must have a userId assigned to the socket after authentication.

Let me know if this helps..

**Comment by caracal7** [comment] 2021-11-09 07:36
Thanks for response.

Can't reproduce the issue right now because often restart server due active development. 
Changed log level to DEBUG.

**Comment by caracal7** [comment] 2021-11-18 07:10
Still have a problem. No micro services in presence after 3 days of work. But RPCs inside microservices is accessible and records API seem to be work fine. 
Only `record.listen('/my-path/.*', async (topic, response) => {})` in some cases didn't send changes but I don't localize problem yet.

Nothing interesting in logs (DEBUG mode) except 
```
| CLUSTER_LEAVE | kw0i5urp-1jtvcphl7clc0
| CLUSTER_SIZE | The cluster size is now 0
| CLUSTER_JOIN | kw0i5urp-1jtvcphl7clc0
| CLUSTER_SIZE | The cluster size is now 1
```
Maybe it happens after that?

**Comment by jaime-ez** [comment] 2021-11-18 21:45
Did your server restarted in that cluster size change?

**Comment by caracal7** [comment] 2021-11-19 06:27
> Did your server restarted in that cluster size change?

I think no

I have 2 development and 1 production servers running on the same host but at different subdomains with Docker/Traefik. Maybe I need different ports for each server?
I don't need any clustering right now.

Why cluster size is changed? What does it mean?

**Comment by caracal7** [comment] 2021-11-22 07:49
I also noticed that record listen is stop working after Presence stopped

my code
```
client.record.listen('microservice#'+endpoint+'/list/.*', async (topic, response) => {
    const match = topic.match(`${endpoint}/list/(.*)`);
    if(!match) return response.reject(); // ??????
    const hash = match[1];

    const snapshot = filterHashes[hash];
    if(!snapshot) return response.reject();  // Hash not found ????
    const { filters, noDeleted } = snapshot;

    let myCursor;
    const recordName = `${endpoint}/list/${hash}`;

    r.table(COLLECTION)
       .filter(filterFn(filters))
       .pluck('id','_deleted',...GRID.filter(i => i.hidden !== true)
       .changes()
       .run(connection, async (err, cursor) => {
           if (err) throw err;
           myCursor = cursor;
           cursor.each(async (err, row) => {
               if (err) throw err;
               const data = await getList(filters, noDeleted);
               const previousResults = await client.record.snapshot('microservice#'+recordName);

               console.log('Changed', recordName); // <------- This not happened after Presence API stop working

               if(!iris.deepEqual(data, previousResults)) {
                   client.record.setData('microservice#'+recordName, { data, schema, options });
               }
           });
       });

    response.onStop(async () => {
        myCursor && myCursor.close && myCursor.close();
        client.record.setData('microservice#'+recordName, {}); // Clear record
    });

    response.accept();
});
```

**Comment by caracal7** [comment] 2021-12-19 16:58
I noted that when I kick out users with using 
```
server.services.httpService.getSocketWrappersForUserId(user_id)
      .forEach(socketWrapper => socketWrapper.close());
```
presence also not updated☝️

**Comment by jaime-ez** [comment] 2021-12-20 03:16
Hi, if you close the socket directly, you won't be calling the onsocket close callback, I think you should do something like this:

```
server.services.httpService.getSocketWrappersForUserId(user_id)
      .forEach(socketWrapper => {
    server.services.connectionEndpoints.forEach(endpoint=> {
         endpoint.onSocketClose.call(endpoint, socketWrapper)
        this.connections.delete(socketWrapper.socket)})
    })
});
```
Take a look at how connections are closed here for example: https://github.com/deepstreamIO/deepstream.io/blob/master/src/services/http/uws/uws-http.ts#L216

- Since presence register a connection listener:
https://github.com/deepstreamIO/deepstream.io/blob/master/src/deepstream.io.ts#L298

- Authenticated socket calls onClientConnected:
https://github.com/deepstreamIO/deepstream.io/blob/master/src/deepstream.io.ts#L345

If you close the socket directly, the onSocketClose callbacks wont be called, and presence depends on that in order to update the distributed state. onSocketClose calls socket.close() and also all other services that are registered to that event.

**Comment by caracal7** [comment] 2021-12-20 19:19
> Hi, if you close the socket directly, you won't be calling the onsocket close callback, I think you should do something like this:

Thanks for response.🙂

`connections.delete(socketWrapper.socket)})` breaks the execution

This code looks like working well. Presence also updated
```
    server.services.httpService.getSocketWrappersForUserId(user_id)
        .forEach(socketWrapper => {
            server.services.connectionEndpoints.forEach(endpoint=> {
                if(endpoint.onSocketClose)
                    endpoint.onSocketClose.call(endpoint, socketWrapper);
            });
            socketWrapper.close();
        })
```

**About subject of this issue...**

I think I found the problem and it's not a deepstream.io problem. 
It's a bug in my code for working with RethinkDB. 

You can close the issue.

**Comment by jaime-ez** [comment] 2021-12-20 19:51
ok glad it worked

**Closed by jaime-ez** 2021-12-20 19:51 UTC
Labels: bug, prioritised, to reproduce
