### ISSUE TITLE
listen does not recover from server restart

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#476] opened 2016-12-09 23:52 UTC
I'm debugging an issue where an active listener is not re subscribed when the deepstream server restarts. I think I've nailed down the issue to here:

https://github.com/deepstreamIO/deepstream.io/blob/master/src/listen/listener-registry.js#L485

I believe it should check for `=== -1` instead of `!== -1`. Please correct me if I'm missing something?

**Comment by ronag** [comment] 2016-12-09 23:57
Basically what I'm seeing is that the listener client does not receive a `SUBSCRIPTION_FOR_PATTERN_FOUND`. I have to restart it after restarting the deepstream server to make it live.

**Comment by yasserf** [comment] 2016-12-11 23:24
```
    if (subscribers && subscribers.indexOf(provider.socketWrapper) !== -1) {
      this._triggerNextProvider(subscriptionName)
      return
    }
```

What this is saying is that if the provider is also a subscriber then ignore it and ask another subscriber to provider the data.

I can see this being an issue if your only provider is already subscribed to the subject and sends both the subscribe and listen down at the same time. 

Commenting out the check as opposed to changing the number results in all the tests passing, so I'm assuming its a edge case that we covered due to paranoia lol.

I would suggested a test that has a single provider for a subscription, gets a match, subscribes and then after server restarts gets a subscription found again. We haven't ran into this issue because we always had more than one listener running redundant, but I'm not too sure why it was there to begin with!

**Comment by ronag** [comment] 2016-12-11 23:36
Yes. Removing it seems to resolve my issue. Will do more testing tomorrow.

**Comment by yasserf** [comment] 2016-12-11 23:42
Cool. I need to write some micro-benchmarks around listening, I'm not sure how it scales when it comes to thousands of connections.

Keep me posted on if you see any odd side effects!

**Comment by yasserf** [comment] 2017-01-10 16:27
This fix had an unfortunate regression which is that providers get told to subscribe immediately after discarding occasionally. We might need to put the line back in, write some tests to guard around it and find another solution.

**Comment by ronag** [comment] 2017-01-19 15:09
@yasserf Any update on this?

**Comment by yasserf** [comment] 2017-02-12 21:30
Hey Ronag,

So I got a fix for this, but its not the.. sanest.

Basically the issue we have is when the server restarts we have no idea who is a subscriber and who is a publisher

The two solutions are:

1) Client listens to connection, when its lost unsubscribes to things it has provided. This is ugly and I'm sure most people won't do this.

2) Server finds a provider than can provide a subscriptionName, but the provider is already subscribed.. odd! So it unsubscribes the record on the provider on behalf of the client and then tells it to continue.

Problem is to unsubscribe a client on its behalf AND allow the client to continue working we need to sort of get that logic into the client too, so its all a bit messy.

Open for suggestions!

**Comment by yasserf** [comment] 2017-02-12 21:42
Just found out we can pretty much solve this by conditionally notifying records (which emits a discarded event) and force the issue only on events. Given events should NOT subscribe to the event ( its a one way emitter pattern ) this should work quite nicely.

**Comment by yasserf** [comment] 2019-06-01 13:46
Fixed in v3 when we dropped the support of getting a record to update and instead using setData

**Closed by yasserf** 2019-06-01 13:46 UTC
Labels: bug, to reproduce
