### ISSUE TITLE
Better healthheck

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#581] opened 2017-02-14 16:32 UTC
The healthcheck endpoint should reflect whether the server is able to process messages in a certain timeout.

**Comment by yasserf** [comment] 2017-02-24 18:55
How would this work exactly? If the health check returns false because its busy.. then it will get killed by whatever is health checking it.

**Comment by yasserf** [comment] 2017-03-12 09:06
Closing as I have no idea how we can improve the health-check callback as intended ( which is if machine is up or not ).

**Closed by yasserf** 2017-03-12 09:06 UTC
