### ISSUE TITLE
_server.close callback never called

### ISSUE THREAD

**Issue by Lalem001** [deepstreamIO/deepstream.io#64] opened 2016-01-12 15:51 UTC
During a server shutdown, when clients are disconnected by the shutdown, the [_server.close callback](https://github.com/hoxton-one/deepstream.io/blob/master/src/message/connection-endpoint.js#L100) is never called.

Perhaps engine.io is **still** accepting connections after close?

**Comment by Lalem001** [comment] 2016-01-12 16:01
To be more specific, I have a timeout of 10 seconds for the server shutdown. If _server.close is being called after 10 seconds, I do not know about it.

I am not using deepstream in production yet, does 10 seconds seem too short to you guys?

**Comment by WolframHempel** [comment] 2016-01-12 16:03
10 seconds should be fine. We've encountered an issue a while ago where TCP ports weren't released for a few minutes by the OS, but that only caused trouble when restarting the server, not when shutting it down. We'll extend our test-suite around closing the server and should hopefully be able to pin down the issue shortly.

**Comment by yasserf** [comment] 2016-02-14 16:49
Perhaps this is an issue where the clients and tcp close before the server, and then engineio closed which means it doesn't actually do anything. Ran into that when writing tests for another issue, be good to see if this can still be duplicated after the next release.

**Comment by yasserf** [comment] 2016-02-14 16:53
@Lalem001 I can't seem to replicate this issue. Is it based on a purely vanilla setup or is their anything that can help me reproduce this?

**Comment by Lalem001** [comment] 2016-02-15 22:32
Simplest steps to reproduce:

- Create/start a basic deepstream server.
- Load deepstream's `test-client` in browser, and **leave open**
- Call server.stop()
  - I call server.stop on <kbd>ctrl</kbd> + <kbd>c</kbd>

The callback is never called. Happens every time.

I see that the server code has been updated since I originally posted. The new line in question starts at [connection-endpoint.js#L128](https://github.com/deepstreamIO/deepstream.io/blob/75dda5ebce4bec8c511356f6f5b729b6d0bc2882/src/message/connection-endpoint.js#L128).

Despite the changes, the issue still occurs.

**Comment by yasserf** [comment] 2016-02-16 09:28
Awesome, will take a look at it and see

**Comment by Lalem001** [comment] 2016-03-03 18:53
Any updates? Have you been able to replicate?

**Comment by adityamenon** [comment] 2016-04-07 13:56
Hi @Lalem001,

> I call server.stop on ctrl + c

Do you mean you're just doing `ctrl+c` on the running `$ node start.js` deepstream instance? (I got mine started with [this file](https://github.com/deepstreamIO/deepstream.io/blob/master/start.js)). Are you doing anything manual like listening to `ctrl+c` yourself, and calling `server.stop()` by yourself? Something like this is what I mean: https://gist.github.com/adityamenon/a8b24d1b6ce45c27f54fb5cbda1029e4

Sorry for the confusion!

**Comment by Lalem001** [comment] 2016-04-07 14:48
Hello @adityamenon,

My stop code basically boils down to:

```javascript
process.on('SIGINT', () => {
  server.once('stopped', () => { process.exit(0); });
  server.once('error', () => { process.exit(1); });
  server.stop();
});
```

This is omitting logging, promises, and many other bits.

I hope this clarifies things for you.

**Comment by adityamenon** [comment] 2016-04-07 17:49
I couldn't replicate the issue & the callback function being passed to `_server.close()` is in fact being called, *when I use a key that is not <kbd>ctrl</kbd>+<kbd>c</kbd>.

My setup steps:
1. Modify `start.js` to look like so:
```
var Deepstream = require( './src/deepstream.io' );
var deepstream = new Deepstream();

process.stdin.on('readable', () => {
  var chunk = process.stdin.read();
  if (null !== chunk && chunk.toString() === "d\n") deepstream.stop();
});

deepstream.start();
```
2. Run `$ node-debug start.js`
3. Have a breakpoint inside the [`_server.close`](https://github.com/deepstreamIO/deepstream.io/blob/21a04653025545f1fb7eff6f6976eb2e59f44024/src/message/connection-endpoint.js#L129) callback.
4. Hit <kbd>d</kbd> then <kbd>Enter</kbd>

I see that the callback is indeed being triggered.

There's a chance that `SIGTERM` behaves a little differently, I will test that.

**Comment by Lalem001** [comment] 2016-04-07 18:14
@adityamenon Are you having a client connect to the test server you have created? Perhaps I was not so clear on that point in my steps to reproduce above.

Here are the steps again, with the step to connect added in.

- Create/start a basic deepstream server.
- Load deepstream's `test-client` in browser, **connect**, and **leave open**
- Call server.stop()
  - I call server.stop on <kbd>ctrl</kbd> + <kbd>c</kbd>

The point is that the server fails to call the callback when it needs to disconnect a client.

**Comment by adityamenon** [comment] 2016-04-07 18:29
Oh yeah, you're actually right.

I just added:
```
process.on('SIGINT', () => {
  deepstream.stop();
})
```
to my `start.js` file. Also, a `console.log()` inside that callback.

Then, *without connecting with a client*, when I did <kbd>Ctrl</kbd>+<kbd>C</kbd>, the callback was called. However when I ran had the `test-client/test-client.html` page open in the browser, then hit <kbd>Ctrl</kbd>+<kbd>C</kbd>, the callback was no longer called.

It was kind of unbelievable for me, I didn't know enough to figure that having a client connected can affect this.

As an aside, is there any way to have `node-debug` ignore `SIGINT` and not stop? It's very annoying to lose debugger abilities when doing testing related to this key combo.

**Comment by adityamenon** [comment] 2016-04-07 18:36
(just to be clear `SIGINT` is not a necessity, the problem is replicated with any other key combo as well as long as a client is connected)

**Comment by yasserf** [comment] 2016-05-12 19:53
Cool, found a few issues:
1) The clients object in engine.io is an object and not an array, so the loop isn't correct
2) Engine.io doesn't clean up on .close, it just closes current conenctions. This means requests will come in, create new sockets and never call the close callback.

That being said, it still doesn't give immediate close callback, so not sure if state is still somewhere.

Old logs:

AUTH_SUCCESSFUL | Wolfram
  engine intercepting request for path "/engine.io/" +6ms
  engine handling "GET" http request "/engine.io/?EIO=3&transport=polling&sid=TcxbSUM0BKlTGSXFAAAA" +3ms
  engine setting new request for existing client +4ms
  engine:polling setting request +0ms
  engine:socket flushing buffer to transport +6ms
  engine:polling writing " ║�4AA" +1ms
  engine:socket executing batch send callback +2ms
  engine intercepting request for path "/engine.io/" +9ms
  engine handling "GET" http request "/engine.io/?EIO=3&transport=polling&sid=TcxbSUM0BKlTGSXFAAAA" +7ms
  engine setting new request for existing client +1ms
  engine:polling setting request +0ms
  engine upgrading existing transport +216ms
  engine:socket might upgrade socket transport from "polling" to "websocket" +2ms
  engine:ws received "2probe" +6ms
  engine:ws writing "3probe" +3ms
  engine:socket writing a noop packet to polling for fast upgrade +102ms
  engine:polling writing " ╔�6" +1ms
  engine:ws received "5" +6ms
  engine:socket got upgrade packet - upgrading +1ms
  engine:polling closing +7ms
  engine:polling transport discarded - closing right away +0ms
  engine closing all open clients +4s
  engine:ws closing +2ms
CLIENT_DISCONNECTED | Wolfram
  engine intercepting request for path "/engine.io/" +13ms
  engine handling "GET" http request "/engine.io/?EIO=3&transport=polling" +3ms
  engine handshaking client "-_nTxxocLJZMdG1rAAAB" +1ms
  engine:socket sending packet "open" ({"sid":"-_nTxxocLJZMdG1rAAAB","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}) +2ms
  engine:polling setting request +1ms
  engine:socket flushing buffer to transport +1ms
  engine:polling writing "      �0{"sid":"-_nTxxocLJZMdG1rAAAB","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}" +1ms
  engine:socket executing batch send callback +1ms
  engine intercepting request for path "/engine.io/" +15ms
  engine handling "GET" http request "/engine.io/?EIO=3&transport=polling&sid=-_nTxxocLJZMdG1rAAAB" +1ms
  engine setting new request for existing client +0ms
  engine:polling setting request +1ms


New logs have nothing after CLIENT_DISCONNECTED.

The server now closes, but still requires about a minute so something must be held up. Wondering if its due to using `.close` instead of `.destroy` in one of the protocols which doesn't force the socket to close...

**Comment by yasserf** [comment] 2016-05-19 07:19
Fixed, but since engine.io closes sockets graceful you have to wait before closes to exit process

**Closed by yasserf** 2016-05-19 07:19 UTC
Labels: in review
