### ISSUE TITLE
Bug: Clients sometimes fails to reconnect

### ISSUE THREAD

**Issue by daviderenger** [deepstreamIO/deepstream.io#771] opened 2017-08-01 11:31 UTC
So this is an issue that rarely happens in a live environment but it happens to us all the time when we are developing. 

The setup is one server hosting the deepstream server and a bunch of other servers that connects to the server with deepstream js-clients and provides RPCs. When the deepstream server restarts all other servers reconnects as they should but sometimes, about 1 out of 20 times one of the connecting servers (RPC-providing client) fails to provide the RPCs. There are no error message on the server nor the client but when trying to call the RPC the "NO_RPC_PROVIDER" error is returned.

This does not happens on all clients at the same time. Restarting the connecting server solves it. Without a restart the client never heals and starts to provide those RPCs again.   

``` 
 clientOptions: {
    maxReconnectAttempts: Infinity,
    reconnectIntervalIncrement: 1500,
    rpcAckTimeout: 20000,
    rpcResponseTimeout: 20000,
    subscriptionTimeout: 20000,
    recordReadAckTimeout: 20000,
    recordReadTimeout: 20000,
    recordDeleteTimeout: 20000,
    heartbeatInterval: 10000,
    maxReconnectInterval: 5000
  }
```

**Comment by yasserf** [comment] 2017-08-13 11:54
Is there any chance you have something we can use to replicate this? We'll make sure to fix it once we can reproduce / write tests against

**Comment by daviderenger** [comment] 2017-08-14 07:15
Hi,

I have a created a minimal reproducing repo, I'll just want to make sure it works before pushing it, I made it break the same way twice yesterday so it can happen but it seems to happen a lot more rarely with my minimal repo than in with our product. It seems that it can take hours before it breaks.

Anyway I managed to see that what is happening is that the client never leaves the reconnecting-state. It is stalled in reconnecting forever. Restarting the server is not helping nor is it timing out and tries again. Just hangs in reconnecting.

I'll push the repo as soon as I see the error again.

**Comment by yasserf** [comment] 2017-08-16 08:37
> Anyway I managed to see that what is happening is that the client never leaves the reconnecting-state. It is stalled in reconnecting forever.

Thats really helpful to know!

**Comment by daviderenger** [comment] 2017-08-16 13:17
>> Anyway I managed to see that what is happening is that the client never leaves the reconnecting-state. It is stalled in reconnecting forever.
> Thats really helpful to know!

Just to clarify, the client is not doing anything after this happens, not reconnecting again but its actually at rest with the state 'reconnecting' somehow.

I'm sorry but I could reproduce the error on my test program at all yesterday :) In total I have got the error 3 times in the test program over a period of 48 hours or something like that, that is many thousands of server restarts. I'm still trying to find out what the difference is compared to our system where it happens many many times everyday...

**Comment by daviderenger** [comment] 2017-08-18 11:29
I did some more digging and the problem might be in ws. I have a fork with uws instead [here](https://github.com/daviderenger/deepstream.io-client-js/tree/uws) and with that client the error is gone. 

Using uws as client in node instead of ws seems logically anyway, same deps on server and client and also uws as a client should be faster, better and stronger than ws. It seems to work really well but a lot of tests is failing :/ Might be something simple to fix, I haven't looked into it.

One problem that I fixed temporary in that branch is that uws is not emitting closed event if the socket never is connected and that will happen every time the server is restarted so the fix is simply to call _tryReconnect in _onError

**Comment by AlexBHarley** [comment] 2017-09-29 10:49
@daviderenger is there any chance we can get the test repo you have? I've tried a multitude of things with:

- multiple providers coming up and down
- server coming up and down
- rpc requestor connecting and disconnecting.

and have not been able to reproduce the issue.

**Comment by daviderenger** [comment] 2017-09-29 11:50
Hi,

I'm sorry but I lost that code. What it did was:
1. Setup a deepstream server
2. Setup a lot of clients that each provides one unique rpc, (I tested with 20, possible the error is triggered faster with a greater number of clients)
3. Restart the server and after a delay call all RPCs, if no one fails, repeat
4. If one or more fails with NO_RPC_PROVIDER, retry again and again with a good interval to see if the RPC starts to be provided. And here is the bug, sometimes the RPC is never provided again.

Running this for a while usually ends up with one RPC that never gets provided until that client is restarted again. Sometimes it takes a couple of minutes sometimes it can take hours.

This used to happen for us in development all the time but after my fix and move to uWS I have never seen it again. So it might be solved by uWS or by the fix a had to do to get uWS to work as a client at all (call _tryReconnect  in _onError) 

I can also mention that we use RPC so that all RPCs should be available, if they are not its probably temporary, server restart or network problem or whatever. So to solve problems during restarts and updates we added a retry functionality in the layer we use to wrap the client, it retries until it hits a timeout and then returns NO_RPS_PROVIDER anyway. This works very well for our case anyway but it would be much wiser to implement the same functionality on server side. Is that something you have considered adding? (https://github.com/briteback/deepstream-utils/blob/master/src/rpc.js)

**Comment by AlexBHarley** [comment] 2017-09-29 15:02
Thanks for that. Could you confirm the versions of the client and server you're using, as well the OS you're using?

**Comment by daviderenger** [comment] 2017-09-29 18:20
Ubuntu 16.04 and 17.04
Node 6.x and 8.x
deepstream.io, hard to say, we have seen this for at least 6 months
deepstream.io-client-js, from a while and latest we had it was on this [commit](https://github.com/deepstreamIO/deepstream.io-client-js/commit/0623cec2e8329c3c12e911c89565bc5ce5dbf6f5) and now as I said we use the forked version mentioned above

**Comment by yasserf** [comment] 2017-09-29 20:58
Does the forked version work constantly the entire time? I'm open to moving to uws if it doesn't have any issues

**Comment by daviderenger** [comment] 2017-09-29 21:02
Yes it is, we have not seen the issue even once since we moved to uWS. We have not seen any other issues either so looks fine except that a lot of tests fail

**Comment by yasserf** [comment] 2017-09-30 10:11
Interesting! We are going to be massively changing the client SDK anyways soon so we can try make sure it works with both and ship with uWS by default

**Comment by yasserf** [comment] 2017-09-30 17:16
Changed to UWS, figured it makes sense todo before the refactor. If you don't have anything else different in your version you could try using our latest client.. I'm deploying it in our staging environment too to see what happens

**Comment by yasserf** [comment] 2017-09-30 17:23
I'm surprised it just worked for you tho, it doesn't seem to deal at all with reconnect events and required a bit of code change.. running it through all our automated tests throughout our stack and theirs a tiny knockon effect

**Comment by yasserf** [comment] 2017-10-01 09:34
Unfortunately had to revert the changes, it appears uws has some pretty big kinks in it such as not being able to distinguish between localhost/127.0.0.1 on macs which makes it pretty flaky =(

**Comment by daviderenger** [comment] 2017-10-02 11:12
Ok, too bad! It works for us because I did this [change](https://github.com/daviderenger/deepstream.io-client-js/commit/bb703b4971f7a5cc31f512be13af059324c5b092), always try to reconnect on error. I wouldn't know about Mac, we are only running it on Linux.

**Comment by yasserf** [comment] 2017-10-02 11:15
yeah that makes sense! I think that needs to go into the normal library too, since a connection error.. is just the connection. No need to ever kill the SDK

**Comment by yasserf** [comment] 2017-10-02 11:15
I will try again when we refactor the codebase (also making it typescript)

**Comment by yasserf** [comment] 2020-05-03 07:39
Closing due to inactivity and no other report on this occurring. Potentially fixed in v4.

**Closed by yasserf** 2020-05-03 07:39 UTC
Labels: bug, to reproduce
