### ISSUE TITLE
Deepstream server crashes in case of incorrect input

### ISSUE THREAD

**Issue by philip-rlt** [deepstreamIO/deepstream.io#509] opened 2016-12-21 14:19 UTC
Server crashes with `TypeError: message.split is not a function` in message-parser.js:53 when message is an ArrayBuffer and not a string. Can be reproduced by sending any binary data.

**Comment by yasserf** [comment] 2017-02-12 13:13
Duplicate of #538 ( although your raised yours first! ). Thank you for raising, we will be fixing this and releasing it in the next few days.

**Closed by yasserf** 2017-02-12 13:13 UTC
