### ISSUE TITLE
Detached mode fails on AWS

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#303] opened 2016-07-27 04:57 UTC
Getting the following error when running `deepstream start -d` on AWS linux

![image](https://cloud.githubusercontent.com/assets/1503717/17164309/5aad31e6-53c7-11e6-8aed-57299a2ca302.png)

**Comment by yasserf** [comment] 2016-07-27 08:20
Duplicate of #246

**Closed by yasserf** 2016-07-27 08:20 UTC
Labels: bug
