### ISSUE TITLE
MULTIPLE_SUBSCRIPTIONS error if the server is temporarily unavailable

### ISSUE THREAD

**Issue by ChristophConrads-deepstreamHub** [deepstreamIO/deepstream.io#501] opened 2016-12-15 13:13 UTC
[zipped demo code](https://github.com/deepstreamIO/deepstream.io/files/654703/multiple-subscriptions-error.zip), run it with `bash run.sh`

If a server is temporarily unavailable, otherwise operational client code start receiving error messages after reestablishing connectivity. Console output (server stdout was redirected to a file, client output by the error message handler is prefixed by `error_handler`):
```
error_handler Can't connect! Deepstream server unreachable on ws://localhost:6020/deepstream connectionError C
error_handler Can't connect! Deepstream server unreachable on ws://localhost:6020/deepstream connectionError C
error_handler b/foo ACK_TIMEOUT R
error_handler b/foo RESPONSE_TIMEOUT R
MULTIPLE_SUBSCRIPTIONS | repeat supscription to "b/foo" by root
error_handler b/foo MULTIPLE_SUBSCRIPTIONS R
VERSION_EXISTS | root tried to update record b/foo to version 1 but it already was 1
```

Expected behavior:
No error messages after reestablishing connectivity.

**Comment by yasserf** [comment] 2016-12-20 10:01
This is great, been looking to nail the cause for a while

**Comment by yasserf** [comment] 2017-02-12 13:15
This is a client issue

**Comment by yasserf** [comment] 2019-07-15 20:03
Fixed in V4

**Closed by yasserf** 2019-07-15 20:03 UTC
Labels: bug, to reproduce
