### ISSUE TITLE
Be able to delete a record's value

### ISSUE THREAD

**Issue by jwanglof** [deepstreamIO/deepstream.io#29] opened 2015-07-23 08:18 UTC
Would be awesome if you guys could implement a way to remove a record's value. E.g.:

```javascript
var record = client.record.get('user/jwanglof')
console.log(record.get());
```
```javascript
Console log:
{
    firstname: 'Johan',
    surname: 'Wanglof',
    pets: [
        {pet_id: 'roger_the_rabbit'},
        {pet_id: 'max_the_cat'},
        {pet_id: 'rosa_the_cow'}
    ]
}
```
Lets say that max_the_cat dies (sorry for being gruesome) and I want to remove it from the pets-list. It would be sweet if I could do a delete on just that record by index (or index-name perhaps?):
```javascript
record.delete('pets[1]');
```

**Comment by yasserf** [comment] 2015-07-24 14:23
Agreed, this feature sounds really useful! We have added it onto our roadmap and will implement it soon. Will keep this thread updated with progress and release date.

**Comment by jwanglof** [comment] 2015-09-25 06:18
What's the status on this feature? =)

**Comment by yasserf** [comment] 2015-09-27 15:42
Just started looking at this, sorry for the long delay.

I'm considering having this done via .set( path, undefined )

A bit keen to keep delete ( which is a very final action ) and record modification separate. 

Also, what kind of callback would you expect? If **Bob** is subscribed to **pets.1** and **John** removed it would **Bob** expect to get undefined back and react accordingly?

Following example is just a brain dump of what issues might arise from that API being used with an Array.

```javascript
petOwner = ds.record.getRecord( 'petOwner ' );

//Bob

function petDetailsChanged( pet ) {
    if( typeof pet === "undefined" ) {
      // pet died =(
      // must now unsubscribe and cleanup, and take into account pets[ 2 ] might now be pets[ 1 ]
   } else {
      //pet status has changed! ( and is still totally alive )
   }
}

petOwner.subscribe( 'pets.1', petDetailsChanged );
petOwner.subscribe( 'pets.2', petDetailsChanged);

//John
petOwner.set( "pets.1", undefined );
```

@jwanglof  @WolframHempel Thoughts?

**Comment by jwanglof** [comment] 2015-09-27 15:55
My initial thought is that the dump seems to make sense, I can talk to my CTO tomorrow and see if he has any thoughts as well.

But, it makes sense that the developer, and not the API, needs to take care when a record is being changed in any way imo, but the API probably needs to make sure that the array is in a correct order so that index `1` isn't undefined when there is an index `2` (this shouldn't be a problem with JavaScript though).

One thing to think about when creating the document for this feature is that this must be really clear so the developers knows how to handle with this =)

And it seems smart to keep delete and record modification separate for sure.

**Comment by yasserf** [comment] 2016-05-15 11:42
Closing as duplicate of #119

**Closed by yasserf** 2016-05-15 11:42 UTC
Labels: feature, in progress
