### ISSUE TITLE
Lists not saved to RethinkDB

### ISSUE THREAD

**Issue by Tetraib** [deepstreamIO/deepstream.io#297] opened 2016-07-21 22:23 UTC
Hi,
Is it the intended purpose that lists are not saved to RethinkDB ?

**Comment by ronag** [comment] 2016-07-21 22:42
Lists are implemented on top of records. So list should be saved just like any record.

**Comment by Tetraib** [comment] 2016-07-23 19:28
For some reason my lists' contents are not saved to the rethinkdb.
It just save the list name.

**Comment by yasserf** [comment] 2016-07-24 11:47
hey @Tetraib,

This might be a side effect of storing an array as the topmost element. Previously to 1.0 it was within the _ds which meant it was serialized differently.

I'll look into this ASAP and either tell you if the problem isn't with us or put out a fix.

**Comment by yasserf** [comment] 2016-07-24 21:29
This is indeed the issue, working on it now. Since data is stored top-level and are also arrays adding meta data to it just gets ignored ( rightfully ) by the database. Good find!

**Comment by yasserf** [comment] 2016-07-24 22:10
This is now fixed in 1.0.2, and also in the mongodb and other connectors.

The fix involves it having to live under `__dsList` as we can't allow an array to live in the topmost level and also have ds data associated. This might be considered a breaking change, but since it never was saved since 1.0 I don't think it deserves a major version bounce.

Thanks again!

**Closed by yasserf** 2016-07-24 22:10 UTC
Labels: bug, in progress
