### ISSUE TITLE
Debounce/Batch Storage Requests

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#254] opened 2016-07-01 15:44 UTC
We're having issue with lots of updates causing the storage connector to be unable to keep up and ending up with `STORAGE_RETREIVAL_TIMEOUT`.

Given the loose guarantees deepstream provides. Would it be possible to debounce/batch storage updates? Especially when the same record is updated several dozen times in the same second.

**Comment by yasserf** [comment] 2016-07-10 15:21
This is on our near roadmap since it shouldn't be too hard to implement.

Closing as a duplicate of 
https://github.com/deepstreamIO/deepstream.io/issues/102

**Closed** 2016-07-10 15:21 UTC
Labels: duplicate
