### ISSUE TITLE
Disconnected client record subscriptions are not removed

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#319] opened 2016-08-06 21:58 UTC
I have a scenario where a a client incorrectly subscribed to 100:s of records. After killing it's connection I've noticed that deepstream still considers all the records subscribed, so even when I restart a listener service, it will start listening to those 100:s of records that no one is actually using...

The only way to recover is to restart the deepstream server.

**Comment by yasserf** [comment] 2016-08-07 09:37
That's pretty severe. Can you replicate that with a very basic test case?

**Comment by WolframHempel** [comment] 2016-08-07 09:43
Could you please let us know if you call close()? By design it keeps
subscriptions during a connection loss so that it can resubscribe them once
the connection comes back.

On 7 Aug 2016 11:37 a.m., "Yasser Fadl" <notifications@github.com> wrote:

That's pretty severe. Can you replicate that with a very basic test case?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/deepstreamIO/deepstream.io/issues/319#issuecomment-238072962>,
or mute the thread

**Comment by ronag** [comment] 2016-08-07 09:58
@WolframHempel: `close´ is not called, the client is "killed" through a page reload.

**Comment by ronag** [comment] 2016-08-07 10:01
Looking at the code I can't see handling of a non-graceful client disconnect.

**Comment by ronag** [comment] 2016-08-07 10:07
To me it looks like https://github.com/deepstreamIO/deepstream.io/blob/master/src/message/socket-wrapper.js never emits 'close'.

**Comment by WolframHempel** [comment] 2016-08-07 10:12
It's not the socketWrapper that emit's close, it's the socket itself. For the TCP socket this happens [here](https://github.com/deepstreamIO/deepstream.io/blob/master/src/tcp/tcp-socket.js#L156), for engine.io it happens from within its socket. The subscription registry listens for that event [here](https://github.com/deepstreamIO/deepstream.io/blob/master/src/utils/subscription-registry.js#L97) and calls unsubscribe for everthing the socket was subscribed to on close. Once the last subscription is removed, it will notify subscriptionListeners [here](https://github.com/deepstreamIO/deepstream.io/blob/master/src/utils/subscription-registry.js#L139).  The listener-registry is such a SubscriptionListener and should be notified [here](https://github.com/deepstreamIO/deepstream.io/blob/master/src/utils/listener-registry.js#L122). Generally, subscriptions were cleared up reliably on disconnect. It would be good to know if there's another factor that might play into it that creates the problem

**Comment by ronag** [comment] 2016-08-07 10:13
@WolframHempel: Yeap, makes total sense. I'm going to see and try to reproduce today. I'll get back with more information if/once I have it.

**Comment by WolframHempel** [comment] 2016-08-07 10:14
thanks, much appreciated :-)

**Comment by yasserf** [comment] 2016-08-07 16:21
Update:

I been working a bit on the provider side on the client and I noticed this behavior happen as well.

What I noticed though was it didn't happen consistently, and it appears the the server doesn't get told immediately when the socket closes if I forced close ( in this case my java app). This ties in to what Wolfram said. 

Thinking once we implement heart beats this might be able to fix the issue of noticing "dead" clients, but I'm not sure how much we can do now since its all on an os/network layer level.

Summary, the functionality works as expected, but listeners aren't called as optimistically quick as we would hope.

**Comment by ronag** [comment] 2016-08-07 16:34
Maybe a heartbeat implemented through the socket wrapper?

**Comment by ronag** [comment] 2016-08-07 16:43
Looking at node-nats they don't trust the socket close either and implement a "PING/PONG" heartbeat to detect connectivity.

This also has the advantage of the client being able to fail-over from a non-responsive server, i.e. where there connection is open but the server is non-responsive.

**Comment by yasserf** [comment] 2016-08-07 16:44
Yeah, we have a whole heartbeat story for clients and servers ( for inter deepstream clustering ).

Yeah, we discussed heartbeats as part of listening, but we wanted to keep it separate as should touch multiple other aspect.

**Comment by WolframHempel** [comment] 2016-08-07 16:56
To be sure: engine.io already provides heartbeats, for TCP connections we rely on `setKeepAlive()` - @ronag  do you experience the lack of disconnect detection with a engine.io or TCP client?

**Comment by ronag** [comment] 2016-08-07 16:59
@WolframHempel: I'm getting more unsure. I have a quite complex setup with clients of both types. So it's a bit hard to re-produce consistently.

**Comment by ronag** [comment] 2016-08-07 17:13
@WolframHempel: That's a good start. But it doesn't say whether the deepstream server instance is running properly or not, only that the connection itself is intact.

**Comment by WolframHempel** [comment] 2016-08-07 17:22
Agreed, which is why we're looking into more substantial heartbeat / health check scenarios as @yasserf mentioned. This is increasingly becoming a requirement, especially for more sophisticated load balancing scenarios. Health checks might extend as far as cache/database interaction.

**Comment by yasserf** [comment] 2016-08-28 10:27
Can I close this issue, since it isn't really an issue as much as platform timing until clients are registered as disconnected?

**Comment by yasserf** [comment] 2016-08-28 18:13
Taking that as a yes!

**Closed by yasserf** 2016-08-28 18:13 UTC
