### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by Stumblinbear** [deepstreamIO/deepstream.io#965] opened 2019-07-01 23:46 UTC
I'm getting this issue with the windows NPM version.

```
Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_win32_x64_72.node'
```

As I can find no information on this issue (nor can I figure out how to install the correct uWS version for Node 12), I went to download the Windows build of Deepstream. Though the website links to a 404 page, and no windows build for 4.0.0 seems to exist in the releases. Is there one available, or are there instructions on how to make a windows build?

**Comment by yasserf** [comment] 2019-07-15 18:48
Hey! So new builds will use ws instead of uws to get around this issue. If you have a windows machine be great if you can verify that it works for me!

**Comment by yasserf** [comment] 2019-07-15 18:52
Closing as duplicate of #935

**Closed by yasserf** 2019-07-15 18:52 UTC

**Comment by yasserf** [comment] 2019-07-15 18:53
Actually this issue seems to be more based on the issue UWS doesn't run with node 12 and wasn't based on the binary issue. This should have been fixed in a previous release. Let me know if otherwise.
